export const DUMMY_KOS = [
  {
    id: 1,
    name: "Kost Menteng Harmony",
    city: "Jakarta",
    address: "Jl. Teuku Umar No.12, Menteng, Jakarta Pusat",
    price: 3500000,
    type: "Campur",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=400",
    rating: 4.8,
    sqft: 16,
    facilities: ["AC", "WiFi", "Kamar Mandi Dalam", "Laundry"],
    owner: { name: "Bpk. Haris", verified: true },
  },
  {
    id: 2,
    name: "Griya Depok Asri",
    city: "Depok",
    address: "Jl. Kukusan No.45, Beji, Depok",
    price: 1200000,
    type: "Putri",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=400",
    rating: 4.5,
    sqft: 12,
    facilities: ["WiFi", "Kamar Mandi Dalam", "Kasur"],
    owner: { name: "Ibu Siti", verified: true },
  },
  {
    id: 3,
    name: "Bogor Rain Residenz",
    city: "Bogor",
    address: "Jl. Bangbarung Raya No.10, Bogor Utara",
    price: 1800000,
    type: "Putra",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=400",
    rating: 4.6,
    sqft: 15,
    facilities: ["AC", "Parkir Motor", "Dapur Umum"],
    owner: { name: "Bpk. Andi", verified: false },
  },
  {
    id: 4,
    name: "Dago View Apartment",
    city: "Bandung",
    address: "Jl. Ir. H. Juanda No.150, Dago Atas, Bandung",
    price: 2500000,
    type: "Campur",
    image: "https://images.unsplash.com/photo-1554995207-c18c20360a59?auto=format&fit=crop&q=80&w=400",
    rating: 4.9,
    sqft: 20,
    facilities: ["AC", "Kolam Renang", "Gym"],
    owner: { name: "Ibu Maya", verified: true },
  },
  {
    id: 5,
    name: "Malioboro House",
    city: "Yogyakarta",
    address: "Jl. Sosrowijayan No.25, Malioboro, Yogyakarta",
    price: 1000000,
    type: "Putra",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=400",
    rating: 4.7,
    sqft: 9,
    facilities: ["WiFi", "Kamar Mandi Luar", "Parkir"],
    owner: { name: "Ibu Sri", verified: true },
  },
  {
    id: 6,
    name: "Batu Mejan Residence",
    city: "Bali",
    address: "Jl. Pantai Batu Mejan No.8, Canggu, Bali",
    price: 4500000,
    type: "Campur",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=400",
    rating: 4.9,
    sqft: 25,
    facilities: ["Private Bathroom", "AC", "Pool", "Kitchen"],
    owner: { name: "Bli Wayan", verified: true },
  },
  {
    id: 7,
    name: "Soe-Hatt Luxury Suite",
    city: "Malang",
    address: "Jl. Soekarno Hatta No.2, Malang",
    price: 2200000,
    type: "Putri",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400",
    rating: 4.8,
    sqft: 18,
    facilities: ["AC", "Laundry", "Cleaning Service"],
    owner: { name: "Bpk. Rahmat", verified: true },
  },
  {
    id: 8,
    name: "Nagoya Hill Kost",
    city: "Batam",
    address: "Jl. Teuku Umar No.5, Lubuk Baja, Batam",
    price: 1500000,
    type: "Campur",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=400",
    rating: 4.4,
    sqft: 14,
    facilities: ["WiFi", "Kamar Mandi Dalam", "TV"],
    owner: { name: "Ibu Lina", verified: false },
  },
  {
    id: 9,
    name: "Medan City Bed",
    city: "Medan",
    address: "Jl. S. Parman No.10, Medan City",
    price: 1300000,
    type: "Putra",
    image: "https://images.unsplash.com/photo-1499955085172-a104c9463ece?auto=format&fit=crop&q=80&w=400",
    rating: 4.5,
    sqft: 12,
    facilities: ["WiFi", "Parkir Luas", "Meja Belajar"],
    owner: { name: "Bpk. Syarif", verified: true },
  },
];
